version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
      - am7  # Connect the service to the existing network

networks:
  am7:  # Reference the existing network
    external: true  # Indicate that this network is already created outside of this Compose file

